name: run_updateRepo

on:
  push:
    push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: pullGitHub
      run: |
        curl https://uvt.kumpeapps.com/pullGitHub.php
