name: run_updateRepo

on:
  push:
    push:
    branches: [ "PreProd" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: pullGitHub
      run: |
        curl https://preprod.kumpeapps.com/uvt/pullGitHub.php
